name: Trivy Security Scan

on:
  push:
    branches: [ "main", "master" ]  
  pull_request:
    branches: [ "main", "master" ]  

jobs:
  trivy-scan:
    name: Run Trivy Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'  # Scan filesystem (source code, bao gồm cả dependency)
          security-checks: 'vuln,config,secret'  # Kiểm tra vulnerabilities, misconfigurations, secrets
          format: 'table'  
          severity: 'CRITICAL,HIGH' 
          ignore-unfixed: true  
