name: Trivy Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '*/5 * * * *'  # Cứ 5p chạy 1 lần

jobs:
  update-trivy-db:
    name: Update Trivy DB
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
      - name: Cache Trivy DB
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Update Trivy DB
        run: trivy image --download-db-only

  trivy-scan:
    name: Run Trivy Scanner
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Restore Trivy DB cache
        uses: actions/cache@v4
        with:
          path: ~/.cache/trivy
          key: trivy-db-${{ runner.os }}-${{ github.run_id }}
          restore-keys: |
            trivy-db-${{ runner.os }}-

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'
          security-checks: 'vuln,config,secret'
          format: 'table'
          severity: 'CRITICAL,HIGH'
          ignore-unfixed: true
