name: Trivy Security Scan

on:
  push:
    branches: [ "main", "master" ]  # Chạy khi có thay đổi trên main/master
  pull_request:
    branches: [ "main", "master" ]  # Chạy khi có PR vào main/master

jobs:
  trivy-scan:
    name: Run Trivy Scanner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.30.0
        with:
          scan-type: 'fs'  # Scan filesystem (source code, bao gồm cả dependency)
          security-checks: 'vuln,config,secret'  # Kiểm tra vulnerabilities, misconfigurations, secrets
          format: 'table'  # Định dạng output (có thể thay bằng 'json' nếu cần)
          #exit-code: '1'    # Fail workflow nếu tìm thấy lỗ hổng nghiêm trọng
          severity: 'CRITICAL,HIGH' 
          ignore-unfixed: true  # Bỏ qua các lỗi chưa có bản fix
