jobs:
  update-trivy-db:
    name: Update Trivy DB
    runs-on: ubuntu-latest
    outputs:
      should_update: ${{ steps.should_update.outputs.result }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Restore last update timestamp
        uses: actions/cache@v4
        with:
          path: .last_update
          key: trivy-last-update

      - name: Determine if DB should be updated
        id: should_update
        run: |
          now=$(date +%s)
          if [ -f .last_update ]; then
            last=$(cat .last_update)
            diff=$((now - last))
            echo "Last update: $diff seconds ago"
            if [ "$diff" -lt 300 ]; then
              echo "result=false" >> $GITHUB_OUTPUT
              exit 0
            fi
          fi
          echo "result=true" >> $GITHUB_OUTPUT

      - name: Install Trivy
        if: steps.should_update.outputs.result == 'true'
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget -qO trivy.deb https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy.deb

      - name: Update Trivy DB
        if: steps.should_update.outputs.result == 'true'
        run: |
          trivy image --download-db-only
          date +%s > .last_update

      - name: Save last update timestamp
        if: steps.should_update.outputs.result == 'true'
        uses: actions/cache@v4
        with:
          path: .last_update
          key: trivy-last-update
